### ISSUE TITLE
Contribution Ideas (User Research Centered)

### ISSUE THREAD

**Issue by janet-yu** [intermine/bluegenes-ux-ideas#1]
Hello all! This is just a general discussion about what kind of contributions we should have for this project.

Following the classic UX design process, user research always comes first! So, naturally I feel that our first tasks should center around our users. And as the contribution period progresses, we can have more tasks based on the next steps of the design process.

I suppose some possible deliverables would be several articles from user research such as: user data (from surveys or interviews), user stories, user flows, user personas, or anything else we should build from our data.

Perhaps as a first step, we could have a document of possible user interview questions/an interview protocol? Though I'm not exactly sure how to find users, and whether or not user interviews are a bit too daunting of a first task to tackle...

I also read on the project description that we already have a list of UX concerns to address, so I'm wondering how extensive this list is, and that maybe we can derive some more feasible tasks from that list for our first contributions.

Just an additional note, I'm just a student who's only experience with UX design is through my courses and self-study, so please let me know your thoughts and ideas! :smile:

**Comment by riyasoganii** [comment]
Hi Janet! I was thinking along the same lines. Maybe, once the user has chosen to exit the tab, we could present them with some questions regarding their experience on the site, so we could use that data to further improve the designs. 
And, in the case this is not feasible, or does not present us with feasible data to move forward, as participants, we could work with our own ideas? After some extensive use of the site, we might be able to identify some concerns we can work on.

**Comment by luanafaustini** [comment]
Hey peeps, I found your ideas very good. I've first thought about sending the users that already have a "Mine" an email with questions about usability, but your idea sounds better @riyasoganii!

I also thought about acessibility and I downloaded an extention to audit the website and point improvements that can be made in the HTML code and CSS styles.

I am also still an student and very excited to dive in and learn new things!

**Comment by Rupali2412** [comment]
Hello all, As we have to design a mobile-friendly web service so when I was going through the Intermine website I understood that the website is very data-heavy and it can lead to complex UI for mobile or ignored complex use cases. 
So, I think we can use applications like Hotjar to observe the behaviour of the user on the website. This can give us the very important information about how the user navigates. Or we can always observe the user while performing a task.
Also, we can ask questions about the user's priorities and motivations. Below are some questions that I prepared :
1. Which mine do they use?
2. Do they use search bar for direct navigation or mine list?
3. Do they jump from one mine to another, like while searching through human mine they need to 
    jump to worm mine   ( I'm new to geonomic data analysis. )
4. We also need to know their list creating/saving habit and how can we work on making it more 
   convenient.  ( My mine feature more convenient in the web app. maybe )
Please add to this and suggest changes.
Also, I'm a 3rd-year undergraduate student from India, new to open source and a self-taught designer.

**Comment by yochannah** [comment]
Hey folks! Love the discussions that we've already had here. A few comments / notes: 

- the idea to add an optional pop-up for feedback is great! 
- The InterMine team can also help with access to mailing lists, twitter promotion, blog post announcements, etc. - this might help pull in some of our community members, both maintainers and users of InterMines. 
- Working based on your own ideas via knowledge of heuristics and good practice would be great too, but I think for this project we'd expect at least some user contact. 
- HotJar to use for tracking also sounds like a nice idea. We'd want to check whether it's compatible with the bluegenes architecture which is client-driven. 
- One note for any automated tracking: InterMine has a [privacy policy](https://intermine.readthedocs.io/en/latest/about/privacy-policy/), and we'll need to make sure not to breach it. Mostly this means if we track stuff, we can use it to improve thigns but we can't share it.
- the site is definitely data-heavy, and yes, mobile is a problem! I've yet to figure out any good way to display tabular data well on mobiles. creative ideas welcome! :) 

If y'all want to start lists of interview questions, consider starting a list in .md format and making a pull request to this repo - we can store design materials and specs here and count them as contributions if that sounds useful? (edit to add - if this suggestion makes no sense or you need help let me know and I'll walk you through it :) )

**Comment by roshnidesigns** [comment]
Hi everyone! excellent suggestions from all. I will like to bestow my 2 cents as well.
Considering the fact of building a mobile friendly application (basically a web-app), the app must be usable as well as useful for the people in organization and the communities searching for the data provided here. I hope to improve the overall usability and user experience of the website resulting in better research and usage of the same. Here are some of the suggestions i feel like implementing in the [site](http://bluegenes.apps.intermine.org):

Native look (branding and consistency)

- First of all there is no branding of the site name and usage at all on the [home page](http://bluegenes.apps.intermine.org), second user prefers to stay on the website if they get what is desired. Research shows that users stay on a site for <400ms (also referred as [Doherty threshold](https://lawsofux.com/doherty-threshold)), hence a concern.
- also there is a problem with the consistency and standard of the design material used in the tabs on the top navbar. Consistent design is intuitive design. I think we can accomplish this by integrating [Google Material Design](https://material.io/design/), being flexible it will go easily with the brand of site as well. Since [Aesthetic Usability Effect](https://lawsofux.com/aesthetic-usability-effect) is one of the major aspects of ui design, hence worth mentioning.
- 

Error prevention and handling

- While surfing through the site I noticed several broken links and web-pages connectivity issues, maybe it’s just that the site is not completely built yet but basic error handling and obviousness is really important aspect of any website as it keeps the user engaged and site content more clear and crisp. [Here](https://uxdesign.cc/creating-error-messages-best-practice-in-ux-design-cda3be0f5e16) are the issues I'm pointing to.

Navigation and Control

- I really appreciate the idea of Hot Jar proposed by @Rupali2412 or any other technology to get the heat map of the website, but if it’s not compatible with the ongoing architecture I would suggest to go with the [F-Shaped pattern](https://www.nngroup.com/articles/f-shaped-pattern-reading-web-content/) of website design for initial steps.
- Using tabs for navigation on the website may seem right but on the mobile view i don't think it is a good idea (not handy or usable). Plus the data accessed through the tabs are not similar enough to be used under category. In my opinion we can go through the navigation bar or clean it up using a hamburger menu instead.
- Also for delivering a good user experience it is necessary to find out the functionalities that will answer the customer needs and we need to guide them to specific functions they need most. I think that needs much UX research and analysis, got some of the questions here to start with:

-> How big is the audience for the project, who are they and how significant is the data to them which is provided by us.
-> How do they consume or use the service right now?
-> What do they like or dislike about the product and how often do they use it?
-> Are there some specific demands of the user base that we must be aware of while designing or adding add-on features?
-> How do they use the functionalities offered by the site? Are there enough or more than enough things desired by the customer?

As suggested by some, including feedback system seems nice. While some of the questions above  could be solved if such system is implemented (although i think using popups are kind of annoying for fresh users ), on the other hand some questions require a discussion among the community members itself and a bit of research and user testing as well.
There are many more questions to add, being new to the biological data handled by the site I individually have a lot of questions too.(please do help me out if i go wrong somewhere :) )
Being a ux designer for almost 2 years, above were some of my views over the issue.
I would also like to present the basic low-fidelity prototype of the web-app, may I create a separate issue or pull request for the same?

**Comment by yochannah** [comment]
Please go ahead and make a PR - this might also serve as a great example for others, so thank you! 🚀 

re: your questions

> -> How big is the audience for the project, who are they and how significant is the data to them which is provided by us

There are 30+ intermines around the world, run by different organisations. Users are usually scientists looking for info about genes or proteins, or other biological concepts they are studying. The InterMine core team at Cambridge runs two InterMines - humanmine and flymine - and we get a couple of thousand visitors a month if I recall correctly. Other InterMines may vary. When our two InterMines go down, we'll usually get enquiries so we like to imagine the resources we provide are pretty important for people's day-to-day research ;) 

> -> How do they consume or use the service right now?

Some people use the older JSP-based interfaces, like you can see at https://www.flymine.org. We also have a bunch of traing materials here: https://flymine.readthedocs.io/en/latest/ that might give you an idea of the types of tasks people perform. We'd like to migrate fully to [BlueGenes](http://bluegenes.apps.intermine.org/) instead of the old interface, though. 

For the next few, they is a little harder to provide concrete info on and is something I'm hoping an intern can help us out with! 🚀 

> -> What do they like or dislike about the product and how often do they use it?
> -> Are there some specific demands of the user base that we must be aware of while designing or adding add-on features?
> -> How do they use the functionalities offered by the site? Are there enough or more than enough things desired by the customer?

**Comment by yochannah** [comment]
>While surfing through the site I noticed several broken links and web-pages connectivity issues

If you notice those, please make issues on the [BlueGenes github repo](https://github.com/intermine/bluegenes/issues)! Thanks!! ✨

**Comment by roshnidesigns** [comment]
> -> Please go ahead and make a PR - this might also serve as a great example for others, so thank you! 🚀
>
Thanks for answering the queries and yes i will create a PR soon.
>
> -> For the next few, they is a little harder to provide concrete info on and is something I'm hoping an intern can help us out with! 🚀
>
I see if i could be of some help over here :P

**Comment by pooja2299** [comment]
Hi everyone.
Along with the excellent suggestion given by others. Here are my suggestions on bluegenes and training portal website.
[bluegenes.pdf](https://github.com/intermine/bluegenes-ux-ideas/files/4380667/bluegenes.pdf)

**Comment by yochannah** [comment]
hey all - I'm closing this issue now as the Outreachy internship period has started. Thanks everyone for the delightful discussions and fabulous collaborations! 🚀 ❤️
